<?php if (!defined('__TYPECHO_ROOT_DIR__')) exit; ?>
    
<div id="sidebar1" class="sidebar m-all t-1of3 d-2of7 last-col cf" role="complementary">

					
	<div id="search-2" class="widget mdui-shadow-1 mdui-hoverable widget_search">
		<form role="search" method="get" id="searchform" class="searchform" action="https://wp.xu.ci/">
		<div>
        <!--<label for="s" class="screen-reader-text"></label>-->		
			<script>
  (function() {
    var cx = '003905931720740674900:6yihzsa8610';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:searchbox-only></gcse:searchbox-only>
			
		</div>
		</form>
	</div>	

	<?php if (!empty($this->options->sidebarBlock) && in_array('ShowRecentPosts', $this->options->sidebarBlock)): ?>
		<div id="recent-posts-4" class="widget mdui-shadow-1 mdui-hoverable widget_recent_entries">		
		<h4 class="widgettitle">最新文章</h4>
			<ul>
	<?php $this->widget('Widget_Contents_Post_Recent','pageSize=6')->to($post); ?>
	<?php while($post->next()): ?>
				<li><a href="<?php $post->permalink(); ?>" title="<?php $post->title(); ?>"><?php $post->title(); ?></a></li>
	<?php endwhile; ?>
		  
			</ul>
		</div>
	<?php endif; ?>	

	<?php if (!empty($this->options->sidebarBlock) && in_array('ShowCategory', $this->options->sidebarBlock)): ?>
    <?php
        $sad1=sitebar_ad($this->options->sidebarAD);
        $maxi=floor(count($sad1)/3);
        for($i=1;$i<=$maxi;$i++){
            $icss=($i%2)+1;
            $tmp='<div class="widget widget_ui_textasb mdui-shadow-1 mdui-hoverable"><a class="style0'.$icss.'" href="'.$sad1[$i*3-3].'" target="_blank"><strong>推荐</strong><h2>'.$sad1[$i*3-2].'</h2><p>'.$sad1[$i*3-1].'</p></a></div>';
            echo $tmp;
        }
    ?>
	<?php endif; ?>	
	
	<?php if (!empty($this->options->sidebarBlock) && in_array('ShowRecentComments', $this->options->sidebarBlock)): ?>
	<div id="arpw-widget-3" class="widget mdui-shadow-1 mdui-hoverable arpw-widget-random">
	<h4 class="widgettitle">随机推荐</h4>
		<div class="arpw-random-post ">
		<ul class="arpw-ul">
		<?php getRandomPosts('6');?>
		</ul>
		</div><!-- Generated by https://wordpress.org/plugins/advanced-random-posts-widget/ -->
	</div>	
	<?php endif; ?>	
		
	<?php if (!empty($this->options->sidebarBlock) && in_array('ShowTags', $this->options->sidebarBlock)): ?>
	<div id="tag_cloud-3" class="widget mdui-shadow-1 mdui-hoverable widget_tag_cloud">
	<h4 class="widgettitle">标签云</h4>
	<div class="tagcloud">
		<?php $this->widget('Widget_Metas_Tag_Cloud', 'ignoreZeroCount=1&limit=20')->to($tags); ?>
		<?php while($tags->next()): ?>
			<a href="<?php $tags->permalink(); ?>"><?php $tags->name(); ?> （<?php $tags->count(); ?>）</a>
		<?php endwhile; ?>
	</div>
	</div>
	<?php endif; ?>


	

	
	<div id="linkcat-4" class="widget mdui-shadow-1 mdui-hoverable widget_links"><h4 class="widgettitle">友情链接</h4>
		<ul class="xoxo blogroll">
		<li><a href="https://noo.tw" target="_blank">刷loc新帖</a></li>

		</ul>
	</div>

					
</div>

